services:
  mongodb:
    image: mongo:8.0-rc
    container_name: mongodb-nickname
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.4-rc-alpine
    container_name: redis-nickname
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.2
    container_name: mysql-nickname
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nickname_db
      MYSQL_USER: nickname_user
      MYSQL_PASSWORD: nickname_password
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
  mysql_data:
