spring:
  config:
    import: classpath:application-info.yml
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/nickname_db
    redis:
      repositories:
        enabled: false
      host: localhost
